# Generated by Django 3.2.8 on 2021-10-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageSetup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesmodel',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
