# Generated by Django 3.2.8 on 2021-10-19 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imageSetup', '0002_imagesmodel_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesmodel',
            name='is_saved',
        ),
        migrations.AddField(
            model_name='imagesmodel',
            name='is_saved',
            field=models.ManyToManyField(blank=True, related_name='saved_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
